version: "3"
services:
  web:
    build:
      context: ./
    privileged: true
    command: npm run dev 
    volumes:
      - "./:/app"
    ports:
      - 3000:3000
    container_name: "nuxt"
    tty: true
